name: lmt
channels:
  - defaults
dependencies:
  - python
  - pip
  - ipython
  - numpy
  - scipy
  - cython 
  - matplotlib
  - h5py
  - pyyaml
  - pytest=5.4.*
  - pytest-cov=2.9.*
  - pytest-mock=3.1.*
  - mpmath
  - decorator
  - requests
  - setuptools
  - pip:
    - pint
    - h5py_wrapper
    - -e .
